---
# Create docker directory
- name: Create docker directory
  file: path="{{ playbook_dir }}/docker/{{ item }}" state=directory
  with_items:
    - "spark"
    - "sparkmaster"
    - "sparkslave"
  tags:
    - configuration
# Create docker file
- name: Create Spark Dockerfile
  template: src="{{ item }}-dockerfile.j2" dest="{{ playbook_dir }}/docker/{{ item }}/Dockerfile"
  with_items:
    - "spark"
    - "sparkmaster"
    - "sparkslave"
  tags:
    - configuration
- name: Copy extra files for Spark images
  copy: src="{{ item.file }}" dest="{{ playbook_dir }}/docker/{{ item.name }}/{{ item.file }}"
  with_items:
    - { name: "sparkmaster", file: "confd-watch-sparkmaster" }
    - { name: "sparkslave", file: "confd-watch-sparkslave" }
  tags:
    configuration
- name: Build Spark image
  docker_image: docker_url="tcp://{{ registry_host }}:2375" path="{{ playbook_dir }}/docker/{{ item.name }}" name="{{ item.image }}" state="build"
  with_items:
    - { name: "spark", image: "{{ spark_image_name }}" }
    - { name: "sparkmaster", image: "{{ sparkmaster_image_name }}" }
    - { name: "sparkslave", image: "{{ sparkslave_image_name }}" }
  tags:
    - docker
    - docker_build

- name: Push Spark image to repo
  shell: "docker -H tcp://{{ registry_host }}:2375 push {{ item }}"
  with_items:
    - "{{ spark_image_name }}"
    - "{{ sparkmaster_image_name }}"
    - "{{ sparkslave_image_name }}"
  tags:
    - docker
    - docker_push

- name: Create Units directory
  file: path="{{ playbook_dir }}/units" state=directory
  tags:
    - configuration

- name: Create Spark Units
  template: src="{{ item }}.service.j2" dest="{{ playbook_dir }}/units/{{ item }}.service"
  with_items:
    - "sparkmaster@"
    - "sparkslave@"
  tags:
    - configuration
- name: Submit Spark units
  shell: "fleetctl submit {{ playbook_dir }}/units/{{ item }}.service"
  with_items:
    - "sparkmaster@"
    - "sparkslave@"
  tags:
    - fleet
    - fleet_submit
- name: Start Spark units
  shell: "fleetctl start {{ playbook_dir }}units/{{ item }}.service"
  with_items:
    - "sparkmaster@7100"
    - "sparkslave@7110"
    - "sparkslave@7120"
    - "sparkslave@7130"
    - "sparkslave@7140"
  tags:
    - fleet
    - fleet_start
